### ISSUE TITLE
Similar project

### ISSUE THREAD

**Issue by TomWeishaar** [nthun/metamanager#1]
My advisor met you at a recent conference and realized we're working on similar meta-analysis projects. She asked me to contact you, but I can't find any way to do so other than here on GitHub Issues.

I have a contact form at [http://dev.open-meta.org/app/?Help](http://dev.open-meta.org/app/?Help)

You can also see the project I'm working on there. Please send me your email address so we can discuss how our interests overlap.

**Comment by nthun** [comment]
Hi Tom!

I'm so sorry for the late reply, this somehow flew under my radar!
I've sent you my contact
